### ISSUE TITLE
Formatting Record list as XML or JSON

### ISSUE THREAD

**Issue by jwhitcraft** [chicks/sugarcrm#70]
Currently if you have this code:

``` ruby
    bugs = class_for('Bug')

    @bug_list = bugs.all.sort_by do |a|
      [a.bug_number]
    end

    respond_to do |format|
      format.html # list.html.erb
      format.json { render :json => @bug_list }
      format.xml { render :xml => @bug_list }
    end
```

And you try and go to the json or xml format they don't produce valid json and xml data.  The json just dumps out where as the xml at least tries to produce xml.

**Comment by chicks** [comment]
Oooooh... We just need to figure out what methods these need to respond (probably to_json and to_xml) and patch the base model.

**Comment by davidsulc** [comment]
Hi Jon,

This commit should fix the issue: https://github.com/chicks/sugarcrm/commit/e6514b08d64986df16b52a3bfa20acad89bb0f6b

You can try it out by specifying the git repo in your Gemfile and running `bundle update sugarcrm`.

**Comment by jwhitcraft** [comment]
That didn't fix it.  Here is the error i get this .json

undefined local variable or method `instance_values' for #SugarCRM::Namespace0::Bug:0x007f9387de3bf0

and with xml i just get this back

<sugar-crm-namespace0-bugs type="array"></sugar-crm-namespace0-bugs>

**Comment by davidsulc** [comment]
Is there any way you could post the code to your app somewhere ? Which version of Rails are you using ?

**Comment by jwhitcraft** [comment]
Here is the commit that modified your example code:

https://github.com/jwhitcraft/sugar_on_rails_basic/commit/71009b18ff03711ca7895ed827fa7e76c53b0c36

Here is what i'm using

Rails 3.0.0
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin11.2.0]

let me know if you need anything else.

**Comment by davidsulc** [comment]
Ok, so it seems the Rails integration isn't fully automagical... :-)

Replace line 15 in `app/controllers/sugar_beans_controller.rb` with `format.json { render :json => @beans.to_json }` (note the explicit `to_json` call). That should solve the issue. (XML rendering should be working too.)

**Comment by jwhitcraft** [comment]
Negative,  I'm still getting the errors I got before.

Here is my new code

``` ruby
def list
    @sugar_module = params[:module]
    begin
      @beans = class_for(params[:module]).all(:limit => 10)
    rescue NameError
      @sugar_modules = available_modules.sort
      render :action => "available_modules"
    end

    respond_to do |format|
      format.html # list.html.erb
      format.json { render :json => @beans.to_json }
      format.xml { render :xml => @beans.to_xml }
    end
  end
```

**Comment by davidsulc** [comment]
Yeah, sorry: I was working with the `show` action which worked when adding this block:

```
respond_to do |format|
  format.html
  format.json { render :json => @bean }
  format.xml { render :xml => @bean }
end
```

So now that I've taken a look at the ACTUAL issue, it should be mostly fixed with https://github.com/chicks/sugarcrm/commit/50821297997bb31487ed5b5c80b75e06a39fca59

So run `bundle update sugarcrm` and give it another shot. Since the gem code is "more rails-ish", you can have the following block:

```
respond_to do |format|
  format.html # list.html.erb
  format.json { render :json => @beans }
  format.xml { render :xml => @beans }
end
```

The JSON format will work as advertised, but the XML format will show an empty array. I have no clue why it's behaving this way, and the only tip I can give is that you can get it to generate xml with `render :xml => @beans.map(&:to_xml)`, but you'll get lots of garbage in your markup... I have no clue how to address the "XML list" issue properly. Even stranger is that `render :xml => @bean` will display correct XML markup in the show view...

Let me know if you're still having issues with the JSON.

As a side note, if you're taking a crack at learning Rails, you'll probably be interested in this book: http://davidsulc.com/blog/2011/12/04/rails-3-in-action/ As opposed to many other Rails books, this one teaches to build a rails app like a professional consultant would: test-driven development, sturdy gems, etc. It also goes into advanced topics, so it's great for someone with development experience, but new to the framework. Just my 2 cents ;-)

**Comment by davidsulc** [comment]
Also, I forgot to mention:

In Rails you can now have `respond_to :html, :json, :xml` at the top of your controller (i.e. outside of any method definitions), and then simply put `respond_with(@beans)` for example. If you're doing something more fancy, you can still define a `respond_to` block.

**Comment by jwhitcraft** [comment]
David,

Success!  I'm no so much worried about xml.  I perfer to use json so that is fine.

Thanks for the book.  I will pick that sucker up so i can learn in the proper way. Cheers and thanks for the fixes!

**Comment by davidsulc** [comment]
Yeah, at least json is working, that's a start :-)

You'll enjoy the book: it's by Ryan Biggs (a Rails consultant/developer), and Yehuda Katz (core contributor to jQuery and Rails/Merb). It's also the first book I've come across that takes people from "I don't know Rails" to "I can build a professional-grade maintainable project".

**Comment by radar** [comment]
Yes, please buy my book :)

**Comment by davidsulc** [comment]
Kudos on the book ;-) I think it's a great addition to the Rails landscape, and the only one that brings readers to a "professional level" with Rails. Most other books only add a chapter or two on TDD as an after-thought... Hat tip.
